# Rest api endpoint of etcd
etcd_addr: "http://localhost:2379"

# size of range that id server prefetches from etcd and pushes to local cache
etcd_fetch_range_size: 5000

# max size of range that is served to clients
client_range_max_size: 100